### ISSUE TITLE
Goldorion please help, if you can..

### ISSUE THREAD

**Issue by PSGitHubUser1** [Goldorion/Goldorion#1]
![Capture](https://github.com/Goldorion/Goldorion/assets/90406016/1ba90590-8173-49cc-80c8-9663cece1dc1)

This picture is showing almost everything, what's the issue. Say this to KlemenDEV please if you can.

If you cannot then tell me or remove this 'issue' section, I will understand.

**Comment by Goldorion** [comment]
Contact Pylo using https://www.pylo.co/contact/
